apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kagenti-demo

resources:
  - namespace.yaml
  - weather-agent-deployment.yaml
  - agentcard-cr.yaml

commonLabels:
  demo: sigstore-kagenti
  environment: demo
